-- 20260409_create_tenant_stays.sql
-- 租户租住历史表
CREATE TABLE tenant_stays (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    tenant_id INT UNSIGNED NOT NULL COMMENT '租户ID',
    start_date DATE NOT NULL COMMENT '入住日期',
    end_date DATE DEFAULT NULL COMMENT '迁出日期',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户租住历史';